### PR TITLE
Added a little extra treat

### PR DESCRIPTION
**Pull request by joschua-rgb**

### CODE REVIEW

**Comment by joschua-rgb** [comment]
Any suggestions? 🚀

**Comment by Schmolo** [comment]
LGTM! 👍

**Comment by Schmolo** [comment]
>  [  ](https://camo.githubusercontent.com/66347136f9f512b171ea95694bf02790c21506c56730f6db7b59ec74cdbc201e/68747470733a2f2f6d65646961312e74656e6f722e636f6d2f6d2f55514c43685a717938644d41414141432f6d657267652d6769746875622e676966) [ ](https://camo.githubusercontent.com/66347136f9f512b171ea95694bf02790c21506c56730f6db7b59ec74cdbc201e/68747470733a2f2f6d65646961312e74656e6f722e636f6d2f6d2f55514c43685a717938644d41414141432f6d657267652d6769746875622e676966)

no

**Comment by joschua-rgb** [comment]
Ready to merge?
@Schmolo @DufteDavid

**Pull request closed without merging**
